export const objArray = [
  {
    id: 1,
    path: "/assets/generate-image-of-mountain-sketch.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 2,
    path: "/assets/generate-image-of-nature-sketch.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 3,
    path: "/assets/generate-image-of-water-color-painting-of-american-nature.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 4,
    path: "/assets/generate-image-of-water-color-painting-of-indian_food.jpg",
    dscr: "generate image of mountain sketch",
    tag: "food",
  },
  {
    id: 5,
    path: "/assets/generate-image-of-water-color-painting-of-indian-army.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 6,
    path: "/assets/generate-image-of-water-color-painting-of-ww2_germen_bomber.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 7,
    path: "/assets/generate-image-of-water-color-painting-of-ww2_tank.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 8,
    path: "/assets/generate-village-image-but-it-should-look-like.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 9,
    path: "/assets/generate-image-of-water-color-painting-of-vintage car.jpg",
    dscr: "generate image of mountain sketch",
    tag: "vehicle",
  },
  {
    id: 10,
    path: "/assets/generate-image-of-oil-color-painting-of-lamp.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 11,
    path: "/assets/generate-image-of-oil-color-painting-of-indian-house.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 12,
    path: "/assets/generate-image-of-water-color-painting-of-ship.jpg",
    dscr: "generate image of mountain sketch",
    tag: "vehicle",
  },
  {
    id: 13,
    path: "/assets/generate-image-of-water-color-painting-of-indian-house.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 14,
    path: "/assets/generate-image-of-mountain-sketch.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 15,
    path: "/assets/generate-image-of-nature-sketch.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 16,
    path: "/assets/generate-image-of-water-color-painting-of-american-nature.jpg",
    dscr: "generate image of mountain sketch",
    tag: "nature",
  },
  {
    id: 17,
    path: "/assets/generate-image-of-water-color-painting-of-indian_food.jpg",
    dscr: "generate image of mountain sketch",
    tag: "food",
  },
  {
    id: 18,
    path: "/assets/generate-image-of-water-color-painting-of-indian-army.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 19,
    path: "/assets/generate-image-of-water-color-painting-of-ww2_germen_bomber.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 20,
    path: "/assets/generate-image-of-water-color-painting-of-ww2_tank.jpg",
    dscr: "generate image of mountain sketch",
    tag: "millitary",
  },
  {
    id: 21,
    path: "/assets/generate-village-image-but-it-should-look-like.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 22,
    path: "/assets/generate-image-of-water-color-painting-of-vintage car.jpg",
    dscr: "generate image of mountain sketch",
    tag: "vehicle",
  },
  {
    id: 23,
    path: "/assets/generate-image-of-oil-color-painting-of-lamp.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 24,
    path: "/assets/generate-image-of-oil-color-painting-of-indian-house.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
  {
    id: 25,
    path: "/assets/generate-image-of-water-color-painting-of-ship.jpg",
    dscr: "generate image of mountain sketch",
    tag: "vehicle",
  },
  {
    id: 26,
    path: "/assets/generate-image-of-water-color-painting-of-indian-house.jpg",
    dscr: "generate image of mountain sketch",
    tag: "home",
  },
];
